//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagement.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actual execution time.
        /// </summary>
        public static string Models_AppTask_ActualExecutionTime {
            get {
                return ResourceManager.GetString("Models.AppTask.ActualExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completion date.
        /// </summary>
        public static string Models_AppTask_CompletionDate {
            get {
                return ResourceManager.GetString("Models.AppTask.CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Models_AppTask_Description {
            get {
                return ResourceManager.GetString("Models.AppTask.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Models_AppTask_Name {
            get {
                return ResourceManager.GetString("Models.AppTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Performers.
        /// </summary>
        public static string Models_AppTask_Performers {
            get {
                return ResourceManager.GetString("Models.AppTask.Performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration date.
        /// </summary>
        public static string Models_AppTask_RegistrationDate {
            get {
                return ResourceManager.GetString("Models.AppTask.RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheduled execution time.
        /// </summary>
        public static string Models_AppTask_ScheduledExecutionTime {
            get {
                return ResourceManager.GetString("Models.AppTask.ScheduledExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Models_AppTask_Status {
            get {
                return ResourceManager.GetString("Models.AppTask.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assigned.
        /// </summary>
        public static string Models_Status_Assigned {
            get {
                return ResourceManager.GetString("Models.Status.Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        public static string Models_Status_Completed {
            get {
                return ResourceManager.GetString("Models.Status.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In progress.
        /// </summary>
        public static string Models_Status_InProgress {
            get {
                return ResourceManager.GetString("Models.Status.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Suspended.
        /// </summary>
        public static string Models_Status_Suspended {
            get {
                return ResourceManager.GetString("Models.Status.Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task Management.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create task.
        /// </summary>
        public static string Views_CreateTask_Buttons_Create {
            get {
                return ResourceManager.GetString("Views.CreateTask.Buttons.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string Views_Index_Buttons_Create {
            get {
                return ResourceManager.GetString("Views.Index.Buttons.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string Views_Index_Buttons_Update {
            get {
                return ResourceManager.GetString("Views.Index.Buttons.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CreateTask.
        /// </summary>
        public static string Views_TaskDesc_Buttons_CretateSubtask {
            get {
                return ResourceManager.GetString("Views.TaskDesc.Buttons.CretateSubtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete task.
        /// </summary>
        public static string Views_TaskDesc_Buttons_Delete {
            get {
                return ResourceManager.GetString("Views.TaskDesc.Buttons.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update task.
        /// </summary>
        public static string Views_TaskDesc_Buttons_Update {
            get {
                return ResourceManager.GetString("Views.TaskDesc.Buttons.Update", resourceCulture);
            }
        }
    }
}
